services:
  mongo:
    image: mongo:8
    volumes: [ mongodata:/data/db ]
    healthcheck:
      test: ["CMD","mongosh", "--quiet","--eval","db.adminCommand('ping')"]
      interval: 10s
      
  server:
    build: ./syncboard-server
    environment:
      PORT: 4000
      MONGODB_URI: mongodb://mongo:27017/syncboard
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_ORIGIN: http://localhost:9090
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    depends_on: 
      mongo: 
        condition: service_healthy
        
  client:
    build:
      context: ./syncboard-client
      args: { VITE_API_URL: "" }
    ports: [ "9090:80" ]
    depends_on: [ server ]

volumes: 
  mongodata: